// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.4
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/

#include "PLB46S_addrmap.h"
#include "xparameters.h"

/************************** Function Implementation *************************/
void XEncrypt_Start() {
    XEncrypt_WriteReg(XPAR_ENCRYPT_TOP_0_SPLB_PLB46S_BASEADDR, ap_start_BASEADDR, 0x01);
}

u32 XEncrypt_IsDone() {
    u32 Data;

    Data = XEncrypt_ReadReg(XPAR_ENCRYPT_TOP_0_SPLB_PLB46S_BASEADDR, ap_done_BASEADDR);
    return Data;
}

u32 XEncrypt_IsIdle() {
    u32 Data;

    Data = XEncrypt_ReadReg(XPAR_ENCRYPT_TOP_0_SPLB_PLB46S_BASEADDR, ap_idle_BASEADDR);
    return Data;
}
