// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.2
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================
#include "xil_types.h"
#include "xil_io.h"

// ap_start
#define ap_start_BASEADDR 0x0000

// ap_done
#define ap_done_BASEADDR  0x0004

// ap_idle
#define ap_idle_BASEADDR  0x0008

/***************** Macros (Inline Functions) Definitions *********************/
#define XEncrypt_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))

#define XEncrypt_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))

/************************** Function Prototypes *****************************/
void XEncrypt_Start();
u32 XEncrypt_IsDone();
u32 XEncrypt_IsIdle();
