// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.2
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="encrypt_inst,encrypt,{component_name=encrypt_inst,HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc5vfx70tff1136-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.585000,HLS_SYN_LAT=1816,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=402,HLS_SYN_LUT=773}" *)

module encrypt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        PlainText_dout,
        PlainText_empty_n,
        PlainText_read,
        Key_dout,
        Key_empty_n,
        Key_read,
        CipherText_din,
        CipherText_full_n,
        CipherText_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
input  [7:0] PlainText_dout;
input   PlainText_empty_n;
output   PlainText_read;
input  [7:0] Key_dout;
input   Key_empty_n;
output   Key_read;
output  [7:0] CipherText_din;
input   CipherText_full_n;
output   CipherText_write;

reg ap_done;
reg ap_idle;
reg PlainText_read;
reg Key_read;
reg CipherText_write;
reg   [5:0] ap_CS_fsm = 6'b000000;
reg   [7:0] SBox_address0;
reg    SBox_ce0;
wire   [7:0] SBox_q0;
reg   [7:0] SBox_address1;
reg    SBox_ce1;
wire   [7:0] SBox_q1;
wire   [3:0] RCon_address0;
reg    RCon_ce0;
wire   [7:0] RCon_q0;
wire   [7:0] StateArray_q0;
reg   [7:0] reg_783;
wire   [7:0] StateArray_q1;
reg   [7:0] reg_788;
reg   [7:0] reg_795;
wire   [3:0] i_cast_cast_fu_802_p1;
reg   [3:0] i_cast_cast_reg_1764;
wire   [2:0] i_2_fu_812_p2;
reg   [2:0] i_2_reg_1772;
wire   [2:0] j_1_fu_828_p2;
wire   [0:0] exitcond3_fu_822_p2;
reg    ap_sig_bdd_116;
wire   [3:0] i_1_fu_855_p2;
reg   [3:0] i_1_reg_1785;
wire   [0:0] exitcond2_fu_861_p2;
reg   [7:0] RCon_load_reg_1832;
reg   [7:0] TempKeyCol_1_reg_1837;
wire   [7:0] TempKeyCol_0_fu_955_p2;
reg   [7:0] TempKeyCol_0_reg_1852;
wire   [7:0] p_addr1_fu_960_p5;
reg   [7:0] p_addr1_reg_1857;
wire   [7:0] p_addr3_fu_972_p5;
reg   [7:0] p_addr3_reg_1862;
wire   [7:0] p_addr5_fu_984_p5;
reg   [7:0] p_addr5_reg_1867;
wire   [7:0] j_2_cast_cast_fu_996_p1;
reg   [7:0] j_2_cast_cast_reg_1882;
wire   [2:0] j_3_fu_1006_p2;
reg   [2:0] j_3_reg_1895;
wire   [0:0] exitcond7_fu_1000_p2;
wire   [7:0] TempKeyCol_0_2_fu_1039_p2;
reg   [7:0] TempKeyCol_0_2_reg_1910;
wire   [7:0] TempKeyCol_1_2_fu_1046_p2;
reg   [7:0] TempKeyCol_1_2_reg_1915;
wire   [7:0] TempKeyCol_2_2_fu_1076_p2;
reg   [7:0] TempKeyCol_2_2_reg_1926;
wire   [7:0] TempKeyCol_3_2_fu_1112_p2;
reg   [7:0] TempKeyCol_3_2_reg_1937;
wire   [7:0] p_addr22_fu_1150_p2;
reg   [7:0] p_addr22_reg_1943;
wire   [3:0] i_3_cast_cast_fu_1159_p1;
reg   [3:0] i_3_cast_cast_reg_1948;
wire   [2:0] i_4_fu_1169_p2;
reg   [2:0] i_4_reg_1956;
wire   [2:0] j_5_fu_1185_p2;
wire   [0:0] exitcond6_fu_1179_p2;
reg    ap_sig_bdd_199;
wire   [3:0] i_10_cast_cast_fu_1207_p1;
reg   [3:0] i_10_cast_cast_reg_1969;
wire   [2:0] i_5_fu_1217_p2;
reg   [2:0] i_5_reg_1977;
wire   [3:0] StateArray_addr_gep_fu_303_p3;
reg   [3:0] StateArray_addr_reg_1982;
wire   [0:0] exitcond5_fu_1211_p2;
wire   [3:0] StateArray_addr_1_gep_fu_310_p3;
reg   [3:0] StateArray_addr_1_reg_1987;
wire   [3:0] StateArray_addr_2_gep_fu_317_p3;
reg   [3:0] StateArray_addr_2_reg_1992;
wire   [3:0] StateArray_addr_3_gep_fu_324_p3;
reg   [3:0] StateArray_addr_3_reg_1997;
wire   [3:0] StateArray_addr_4_gep_fu_331_p3;
reg   [3:0] StateArray_addr_4_reg_2002;
wire   [3:0] StateArray_addr_5_gep_fu_338_p3;
reg   [3:0] StateArray_addr_5_reg_2007;
wire   [3:0] StateArray_addr_6_gep_fu_345_p3;
reg   [3:0] StateArray_addr_6_reg_2012;
wire   [3:0] StateArray_addr_7_gep_fu_352_p3;
reg   [3:0] StateArray_addr_7_reg_2017;
wire   [3:0] StateArray_addr_8_gep_fu_359_p3;
reg   [3:0] StateArray_addr_8_reg_2022;
wire   [3:0] StateArray_addr_9_gep_fu_366_p3;
reg   [3:0] StateArray_addr_9_reg_2027;
wire   [3:0] StateArray_addr_10_gep_fu_373_p3;
reg   [3:0] StateArray_addr_10_reg_2032;
wire   [3:0] StateArray_addr_11_gep_fu_380_p3;
reg   [3:0] StateArray_addr_11_reg_2037;
wire   [2:0] j_6_fu_1233_p2;
reg   [2:0] j_6_reg_2045;
reg   [3:0] StateArray_addr_13_reg_2050;
wire   [0:0] exitcond8_fu_1227_p2;
wire   [3:0] r_fu_1256_p2;
reg   [3:0] r_reg_2060;
wire   [5:0] r_cast_cast_fu_1262_p1;
reg   [5:0] r_cast_cast_reg_2066;
wire   [3:0] i11_cast_cast_fu_1272_p1;
reg   [3:0] i11_cast_cast_reg_2074;
wire   [2:0] i_9_fu_1282_p2;
reg   [2:0] i_9_reg_2082;
wire   [0:0] tmp_6_fu_1288_p2;
reg   [0:0] tmp_6_reg_2087;
wire   [0:0] exitcond11_fu_1276_p2;
wire   [2:0] j_9_fu_1303_p2;
reg   [2:0] j_9_reg_2094;
reg   [3:0] StateArray_addr_15_reg_2099;
wire   [0:0] exitcond_fu_1297_p2;
reg   [7:0] StateArray_load_4_reg_2109;
reg   [7:0] x_1_reg_2114;
reg   [7:0] StateArray_load_6_reg_2119;
reg   [7:0] x_2_reg_2124;
reg   [7:0] StateArray_load_8_reg_2129;
reg   [7:0] x_3_reg_2134;
reg   [7:0] StateArray_load_10_reg_2139;
wire   [31:0] i_8_cast_fu_1330_p1;
reg   [31:0] i_8_cast_reg_2144;
wire   [3:0] i_8_cast_cast_fu_1335_p1;
reg   [3:0] i_8_cast_cast_reg_2149;
wire   [2:0] i_14_fu_1345_p2;
reg   [2:0] i_14_reg_2158;
wire   [0:0] exitcond14_fu_1339_p2;
wire   [31:0] p_addr30_cast_fu_1357_p1;
reg   [31:0] p_addr30_cast_reg_2168;
wire   [0:0] grp_fu_767_p3;
reg   [0:0] tmp_15_reg_2178;
wire   [0:0] grp_fu_775_p3;
reg   [0:0] tmp_16_reg_2183;
wire   [31:0] p_addr31_cast_fu_1367_p1;
reg   [31:0] p_addr31_cast_reg_2188;
wire   [31:0] p_addr32_cast_fu_1377_p1;
reg   [31:0] p_addr32_cast_reg_2198;
wire   [7:0] tmp_10_fu_1489_p2;
reg   [7:0] tmp_10_reg_2208;
wire   [7:0] tmp_12_fu_1539_p2;
reg   [7:0] tmp_12_reg_2213;
wire   [7:0] tmp_13_fu_1575_p2;
reg   [7:0] tmp_13_reg_2218;
wire   [3:0] i13_cast_cast_fu_1581_p1;
reg   [3:0] i13_cast_cast_reg_2223;
wire   [2:0] i_11_fu_1591_p2;
reg   [2:0] i_11_reg_2231;
wire   [2:0] j_16_fu_1607_p2;
reg   [2:0] j_16_reg_2239;
wire   [31:0] p_addr34_cast_fu_1624_p1;
reg   [31:0] p_addr34_cast_reg_2244;
wire   [0:0] exitcond17_fu_1601_p2;
wire   [5:0] i12_cast1_fu_1629_p1;
reg   [5:0] i12_cast1_reg_2254;
wire   [3:0] i12_cast_fu_1633_p1;
reg   [3:0] i12_cast_reg_2259;
wire   [2:0] i_13_fu_1643_p2;
reg   [2:0] i_13_reg_2267;
wire   [2:0] j_14_fu_1663_p2;
reg   [2:0] j_14_reg_2275;
reg   [3:0] StateArray_addr_21_reg_2280;
wire   [0:0] exitcond15_fu_1657_p2;
wire   [3:0] i_6_cast_cast_fu_1716_p1;
reg   [3:0] i_6_cast_cast_reg_2290;
wire   [2:0] i_7_fu_1726_p2;
reg   [2:0] i_7_reg_2298;
wire   [2:0] j_8_fu_1742_p2;
reg   [2:0] j_8_reg_2306;
wire   [0:0] exitcond12_fu_1736_p2;
reg   [3:0] StateArray_address0;
reg    StateArray_ce0;
reg    StateArray_we0;
reg   [7:0] StateArray_d0;
reg   [3:0] StateArray_address1;
reg    StateArray_ce1;
reg    StateArray_we1;
reg   [7:0] StateArray_d1;
reg   [7:0] ExpandedKey_address0;
reg    ExpandedKey_ce0;
reg    ExpandedKey_we0;
reg   [7:0] ExpandedKey_d0;
wire   [7:0] ExpandedKey_q0;
reg   [7:0] ExpandedKey_address1;
reg    ExpandedKey_ce1;
reg    ExpandedKey_we1;
reg   [7:0] ExpandedKey_d1;
wire   [7:0] ExpandedKey_q1;
reg   [3:0] StateArrayTmp_address0;
reg    StateArrayTmp_ce0;
reg    StateArrayTmp_we0;
reg   [7:0] StateArrayTmp_d0;
wire   [7:0] StateArrayTmp_q0;
reg   [2:0] i_reg_517;
reg   [2:0] j_reg_528;
wire   [0:0] exitcond1_fu_806_p2;
reg   [3:0] indvar1_reg_539;
reg   [7:0] TempKeyCol_3_1_reg_551;
reg   [7:0] TempKeyCol_2_1_reg_561;
reg   [7:0] TempKeyCol_1_1_reg_571;
reg   [7:0] TempKeyCol_0_1_reg_581;
reg   [2:0] j_2_reg_591;
reg   [2:0] i_3_reg_602;
reg   [2:0] j_4_reg_613;
wire   [0:0] exitcond4_fu_1163_p2;
reg   [2:0] i_10_reg_624;
reg   [2:0] j_10_reg_635;
reg   [3:0] indvar_reg_646;
wire   [0:0] exitcond13_fu_1637_p2;
reg   [2:0] i11_reg_657;
wire   [0:0] exitcond9_fu_1266_p2;
reg   [2:0] j11_reg_668;
reg   [2:0] i_8_reg_679;
reg   [2:0] i13_reg_690;
reg   [2:0] j_15_reg_701;
wire   [0:0] exitcond16_fu_1585_p2;
reg   [2:0] i12_reg_712;
reg   [2:0] j12_reg_726;
reg   [2:0] i_6_reg_737;
reg   [2:0] j_7_reg_748;
wire   [0:0] exitcond10_fu_1720_p2;
wire   [31:0] p_addr10_cast_fu_845_p1;
wire   [31:0] p_addr3_cast_fu_879_p1;
wire   [31:0] p_addr5_cast_fu_896_p1;
wire   [31:0] indvar1_cast_fu_850_p1;
wire   [31:0] p_addr7_cast_fu_913_p1;
wire   [31:0] p_addr8_cast_fu_930_p1;
wire   [31:0] tmp_fu_935_p1;
wire   [31:0] tmp_1_fu_940_p1;
wire   [31:0] tmp_2_fu_945_p1;
wire   [31:0] tmp_3_fu_950_p1;
wire   [31:0] p_addr11_cast_fu_1024_p1;
wire   [31:0] p_addr12_cast_fu_1034_p1;
wire   [31:0] p_addr13_cast_fu_1056_p1;
wire   [31:0] p_addr16_cast_fu_1071_p1;
wire   [31:0] p_addr14_cast_fu_1086_p1;
wire   [31:0] p_addr18_cast_fu_1107_p1;
wire   [31:0] p_addr20_cast_fu_1134_p1;
wire   [31:0] p_addr22_cast_fu_1155_p1;
wire   [31:0] p_addr24_cast_fu_1202_p1;
wire   [31:0] p_addr26_cast_fu_1250_p1;
wire   [31:0] p_addr29_cast_fu_1320_p1;
wire   [31:0] tmp_s_fu_1325_p1;
wire   [31:0] p_addr36_cast_fu_1680_p1;
wire   [31:0] p_addr40_cast_fu_1711_p1;
wire   [31:0] p_addr27_cast_fu_1759_p1;
wire   [7:0] grp_fu_760_p2;
wire   [7:0] tmp_7_fu_1438_p2;
wire   [3:0] p_addr9_fu_834_p2;
wire   [3:0] j_cast_cast_fu_818_p1;
wire   [3:0] p_addr8_fu_839_p2;
wire   [7:0] p_addr2_fu_867_p5;
wire   [7:0] p_addr4_fu_884_p5;
wire   [7:0] p_addr6_fu_901_p5;
wire   [7:0] p_addr7_fu_918_p5;
wire   [7:0] p_addr15_fu_1012_p5;
wire   [7:0] p_addr12_fu_1029_p2;
wire   [7:0] p_addr13_fu_1052_p2;
wire   [7:0] p_addr16_fu_1061_p5;
wire   [7:0] p_addr14_fu_1082_p2;
wire   [7:0] p_addr17_fu_1091_p5;
wire   [7:0] p_addr18_fu_1102_p2;
wire   [7:0] p_addr19_fu_1118_p5;
wire   [7:0] p_addr20_fu_1129_p2;
wire   [7:0] p_addr21_fu_1139_p5;
wire   [3:0] p_addr10_fu_1191_p2;
wire   [3:0] j_4_cast_cast_fu_1175_p1;
wire   [3:0] p_addr11_fu_1196_p2;
wire   [3:0] p_addr23_fu_1239_p2;
wire   [3:0] j_10_cast_cast_fu_1223_p1;
wire   [3:0] p_addr24_fu_1244_p2;
wire   [3:0] p_addr26_fu_1309_p2;
wire   [3:0] j11_cast_cast_fu_1293_p1;
wire   [3:0] p_addr27_fu_1314_p2;
wire   [2:0] p_addr28_fu_1351_p2;
wire   [3:0] p_addr29_fu_1362_p2;
wire   [3:0] p_addr30_fu_1372_p2;
wire   [7:0] tmp_4_fu_1382_p2;
wire   [7:0] tmp_8_fu_1395_p2;
wire   [7:0] tmp1_fu_1408_p2;
wire   [7:0] iftmp_cast_cast_fu_1388_p3;
wire   [7:0] iftmp_1_cast_cast_fu_1401_p3;
wire   [7:0] tmp4_fu_1426_p2;
wire   [7:0] tmp3_fu_1420_p2;
wire   [7:0] tmp5_fu_1432_p2;
wire   [7:0] tmp2_fu_1414_p2;
wire   [7:0] tmp6_fu_1459_p2;
wire   [7:0] tmp_9_fu_1445_p2;
wire   [7:0] iftmp_2_cast_cast_fu_1451_p3;
wire   [7:0] tmp9_fu_1477_p2;
wire   [7:0] tmp8_fu_1471_p2;
wire   [7:0] tmp10_fu_1483_p2;
wire   [7:0] tmp7_fu_1465_p2;
wire   [7:0] tmp11_fu_1509_p2;
wire   [7:0] tmp_11_fu_1495_p2;
wire   [7:0] iftmp_3_cast_cast_fu_1501_p3;
wire   [7:0] tmp14_fu_1527_p2;
wire   [7:0] tmp13_fu_1521_p2;
wire   [7:0] tmp15_fu_1533_p2;
wire   [7:0] tmp12_fu_1515_p2;
wire   [7:0] tmp16_fu_1545_p2;
wire   [7:0] tmp19_fu_1563_p2;
wire   [7:0] tmp18_fu_1557_p2;
wire   [7:0] tmp20_fu_1569_p2;
wire   [7:0] tmp17_fu_1551_p2;
wire   [3:0] p_addr33_fu_1613_p2;
wire   [3:0] j_12_cast_cast_fu_1597_p1;
wire   [3:0] p_addr34_fu_1618_p2;
wire   [3:0] p_addr31_fu_1669_p2;
wire   [3:0] j14_cast_cast_fu_1653_p1;
wire   [3:0] p_addr32_fu_1674_p2;
wire   [5:0] p_addr35_fu_1685_p2;
wire   [5:0] p_addr36_fu_1690_p2;
wire   [7:0] p_addr38_cast_fu_1695_p1;
wire   [7:0] p_addr37_fu_1699_p2;
wire   [7:0] j14_cast_cast1_fu_1649_p1;
wire   [7:0] p_addr38_fu_1705_p2;
wire   [3:0] p_addr_fu_1748_p2;
wire   [3:0] j_7_cast_cast_fu_1732_p1;
wire   [3:0] p_addr25_fu_1753_p2;
reg   [5:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st0_fsm_0 = 6'b000000;
parameter    ap_ST_st1_fsm_1 = 6'b000001;
parameter    ap_ST_st2_fsm_2 = 6'b000010;
parameter    ap_ST_st3_fsm_3 = 6'b000011;
parameter    ap_ST_st4_fsm_4 = 6'b000100;
parameter    ap_ST_st5_fsm_5 = 6'b000101;
parameter    ap_ST_st6_fsm_6 = 6'b000110;
parameter    ap_ST_st7_fsm_7 = 6'b000111;
parameter    ap_ST_st8_fsm_8 = 6'b001000;
parameter    ap_ST_st9_fsm_9 = 6'b001001;
parameter    ap_ST_st10_fsm_10 = 6'b001010;
parameter    ap_ST_st11_fsm_11 = 6'b001011;
parameter    ap_ST_st12_fsm_12 = 6'b001100;
parameter    ap_ST_st13_fsm_13 = 6'b001101;
parameter    ap_ST_st14_fsm_14 = 6'b001110;
parameter    ap_ST_st15_fsm_15 = 6'b001111;
parameter    ap_ST_st16_fsm_16 = 6'b010000;
parameter    ap_ST_st17_fsm_17 = 6'b010001;
parameter    ap_ST_st18_fsm_18 = 6'b010010;
parameter    ap_ST_st19_fsm_19 = 6'b010011;
parameter    ap_ST_st20_fsm_20 = 6'b010100;
parameter    ap_ST_st21_fsm_21 = 6'b010101;
parameter    ap_ST_st22_fsm_22 = 6'b010110;
parameter    ap_ST_st23_fsm_23 = 6'b010111;
parameter    ap_ST_st24_fsm_24 = 6'b011000;
parameter    ap_ST_st25_fsm_25 = 6'b011001;
parameter    ap_ST_st26_fsm_26 = 6'b011010;
parameter    ap_ST_st27_fsm_27 = 6'b011011;
parameter    ap_ST_st28_fsm_28 = 6'b011100;
parameter    ap_ST_st29_fsm_29 = 6'b011101;
parameter    ap_ST_st30_fsm_30 = 6'b011110;
parameter    ap_ST_st31_fsm_31 = 6'b011111;
parameter    ap_ST_st32_fsm_32 = 6'b100000;
parameter    ap_ST_st33_fsm_33 = 6'b100001;
parameter    ap_ST_st34_fsm_34 = 6'b100010;
parameter    ap_ST_st35_fsm_35 = 6'b100011;
parameter    ap_ST_st36_fsm_36 = 6'b100100;
parameter    ap_ST_st37_fsm_37 = 6'b100101;
parameter    ap_ST_st38_fsm_38 = 6'b100110;
parameter    ap_ST_st39_fsm_39 = 6'b100111;
parameter    ap_ST_st40_fsm_40 = 6'b101000;
parameter    ap_ST_st41_fsm_41 = 6'b101001;
parameter    ap_ST_st42_fsm_42 = 6'b101010;
parameter    ap_ST_st43_fsm_43 = 6'b101011;
parameter    ap_ST_st44_fsm_44 = 6'b101100;
parameter    ap_ST_st45_fsm_45 = 6'b101101;
parameter    ap_ST_st46_fsm_46 = 6'b101110;
parameter    ap_ST_st47_fsm_47 = 6'b101111;
parameter    ap_ST_st48_fsm_48 = 6'b110000;
parameter    ap_ST_st49_fsm_49 = 6'b110001;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_4 = 32'b00000000000000000000000000000100;
parameter    ap_const_lv32_5 = 32'b00000000000000000000000000000101;
parameter    ap_const_lv32_6 = 32'b00000000000000000000000000000110;
parameter    ap_const_lv32_7 = 32'b00000000000000000000000000000111;
parameter    ap_const_lv32_8 = 32'b00000000000000000000000000001000;
parameter    ap_const_lv32_A = 32'b00000000000000000000000000001010;
parameter    ap_const_lv32_9 = 32'b00000000000000000000000000001001;
parameter    ap_const_lv32_B = 32'b00000000000000000000000000001011;
parameter    ap_const_lv32_F = 32'b00000000000000000000000000001111;
parameter    ap_const_lv32_E = 32'b00000000000000000000000000001110;
parameter    ap_const_lv32_D = 32'b00000000000000000000000000001101;
parameter    ap_const_lv32_C = 32'b00000000000000000000000000001100;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_1 = 3'b001;
parameter    ap_const_lv4_2 = 4'b0010;
parameter    ap_const_lv4_1 = 4'b0001;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv8_7 = 8'b00000111;
parameter    ap_const_lv8_B = 8'b00001011;
parameter    ap_const_lv8_F = 8'b00001111;
parameter    ap_const_lv8_3 = 8'b00000011;
parameter    ap_const_lv8_4 = 8'b00000100;
parameter    ap_const_lv8_8 = 8'b00001000;
parameter    ap_const_lv8_C = 8'b00001100;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_C = 4'b1100;
parameter    ap_const_lv8_1 = 8'b00000001;
parameter    ap_const_lv8_1B = 8'b00011011;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv6_2 = 6'b000010;
parameter    ap_const_lv8_2 = 8'b00000010;
parameter    ap_true = 1'b1;


encrypt_SBox #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
SBox_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( SBox_address0 ),
    .ce0( SBox_ce0 ),
    .q0( SBox_q0 ),
    .address1( SBox_address1 ),
    .ce1( SBox_ce1 ),
    .q1( SBox_q1 )
);

encrypt_RCon #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
RCon_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( RCon_address0 ),
    .ce0( RCon_ce0 ),
    .q0( RCon_q0 )
);

encrypt_StateArray #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
StateArray_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( StateArray_address0 ),
    .ce0( StateArray_ce0 ),
    .we0( StateArray_we0 ),
    .d0( StateArray_d0 ),
    .q0( StateArray_q0 ),
    .address1( StateArray_address1 ),
    .ce1( StateArray_ce1 ),
    .we1( StateArray_we1 ),
    .d1( StateArray_d1 ),
    .q1( StateArray_q1 )
);

encrypt_ExpandedKey #(
    .DataWidth( 8 ),
    .AddressRange( 176 ),
    .AddressWidth( 8 ))
ExpandedKey_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( ExpandedKey_address0 ),
    .ce0( ExpandedKey_ce0 ),
    .we0( ExpandedKey_we0 ),
    .d0( ExpandedKey_d0 ),
    .q0( ExpandedKey_q0 ),
    .address1( ExpandedKey_address1 ),
    .ce1( ExpandedKey_ce1 ),
    .we1( ExpandedKey_we1 ),
    .d1( ExpandedKey_d1 ),
    .q1( ExpandedKey_q1 )
);

encrypt_StateArrayTmp #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
StateArrayTmp_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( StateArrayTmp_address0 ),
    .ce0( StateArrayTmp_ce0 ),
    .we0( StateArrayTmp_we0 ),
    .d0( StateArrayTmp_d0 ),
    .q0( StateArrayTmp_q0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        RCon_load_reg_1832 <= RCon_q0;
    end
    if (((ap_ST_st16_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
        StateArray_addr_13_reg_2050 <= p_addr26_cast_fu_1250_p1;
    end
    if (((ap_ST_st20_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_1297_p2))) begin
        StateArray_addr_15_reg_2099 <= p_addr29_cast_fu_1320_p1;
    end
    if (((ap_ST_st44_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond15_fu_1657_p2))) begin
        StateArray_addr_21_reg_2280 <= p_addr36_cast_fu_1680_p1;
    end
    if ((ap_ST_st27_fsm_27 == ap_CS_fsm)) begin
        StateArray_load_10_reg_2139 <= StateArray_q1;
    end
    if ((ap_ST_st24_fsm_24 == ap_CS_fsm)) begin
        StateArray_load_4_reg_2109 <= StateArray_q1;
    end
    if ((ap_ST_st25_fsm_25 == ap_CS_fsm)) begin
        StateArray_load_6_reg_2119 <= StateArray_q1;
    end
    if ((ap_ST_st26_fsm_26 == ap_CS_fsm)) begin
        StateArray_load_8_reg_2129 <= StateArray_q1;
    end
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        TempKeyCol_0_1_reg_581 <= TempKeyCol_0_2_reg_1910;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        TempKeyCol_0_1_reg_581 <= TempKeyCol_0_reg_1852;
    end
    if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        TempKeyCol_0_2_reg_1910 <= TempKeyCol_0_2_fu_1039_p2;
    end
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        TempKeyCol_0_reg_1852 <= TempKeyCol_0_fu_955_p2;
    end
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        TempKeyCol_1_1_reg_571 <= TempKeyCol_1_2_reg_1915;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        TempKeyCol_1_1_reg_571 <= TempKeyCol_1_reg_1837;
    end
    if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        TempKeyCol_1_2_reg_1915 <= TempKeyCol_1_2_fu_1046_p2;
    end
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        TempKeyCol_1_reg_1837 <= SBox_q1;
    end
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        TempKeyCol_2_1_reg_561 <= TempKeyCol_2_2_reg_1926;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        TempKeyCol_2_1_reg_561 <= SBox_q0;
    end
    if ((ap_ST_st10_fsm_10 == ap_CS_fsm)) begin
        TempKeyCol_2_2_reg_1926 <= TempKeyCol_2_2_fu_1076_p2;
    end
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        TempKeyCol_3_1_reg_551 <= TempKeyCol_3_2_reg_1937;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        TempKeyCol_3_1_reg_551 <= SBox_q1;
    end
    if ((ap_ST_st11_fsm_11 == ap_CS_fsm)) begin
        TempKeyCol_3_2_reg_1937 <= TempKeyCol_3_2_fu_1112_p2;
    end
    if ((ap_ST_st19_fsm_19 == ap_CS_fsm)) begin
        i11_cast_cast_reg_2074[0] <= i11_cast_cast_fu_1272_p1[0];
        i11_cast_cast_reg_2074[1] <= i11_cast_cast_fu_1272_p1[1];
        i11_cast_cast_reg_2074[2] <= i11_cast_cast_fu_1272_p1[2];
    end
    if (((ap_ST_st18_fsm_18 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_1266_p2))) begin
        i11_reg_657 <= ap_const_lv3_0;
    end else if (((ap_ST_st20_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_1297_p2))) begin
        i11_reg_657 <= i_9_reg_2082;
    end
    if ((ap_ST_st43_fsm_43 == ap_CS_fsm)) begin
        i12_cast1_reg_2254[0] <= i12_cast1_fu_1629_p1[0];
        i12_cast1_reg_2254[1] <= i12_cast1_fu_1629_p1[1];
        i12_cast1_reg_2254[2] <= i12_cast1_fu_1629_p1[2];
    end
    if ((ap_ST_st43_fsm_43 == ap_CS_fsm)) begin
        i12_cast_reg_2259[0] <= i12_cast_fu_1633_p1[0];
        i12_cast_reg_2259[1] <= i12_cast_fu_1633_p1[1];
        i12_cast_reg_2259[2] <= i12_cast_fu_1633_p1[2];
    end
    if (((ap_ST_st44_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond15_fu_1657_p2))) begin
        i12_reg_712 <= i_13_reg_2267;
    end else if ((((ap_ST_st40_fsm_40 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond16_fu_1585_p2)) | ((ap_ST_st33_fsm_33 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_6_reg_2087)))) begin
        i12_reg_712 <= ap_const_lv3_0;
    end
    if ((ap_ST_st40_fsm_40 == ap_CS_fsm)) begin
        i13_cast_cast_reg_2223[0] <= i13_cast_cast_fu_1581_p1[0];
        i13_cast_cast_reg_2223[1] <= i13_cast_cast_fu_1581_p1[1];
        i13_cast_cast_reg_2223[2] <= i13_cast_cast_fu_1581_p1[2];
    end
    if (((ap_ST_st41_fsm_41 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond17_fu_1601_p2))) begin
        i13_reg_690 <= i_11_reg_2231;
    end else if (((ap_ST_st34_fsm_34 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond14_fu_1339_p2))) begin
        i13_reg_690 <= ap_const_lv3_0;
    end
    if ((ap_ST_st15_fsm_15 == ap_CS_fsm)) begin
        i_10_cast_cast_reg_1969[0] <= i_10_cast_cast_fu_1207_p1[0];
        i_10_cast_cast_reg_1969[1] <= i_10_cast_cast_fu_1207_p1[1];
        i_10_cast_cast_reg_1969[2] <= i_10_cast_cast_fu_1207_p1[2];
    end
    if (((ap_ST_st16_fsm_16 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
        i_10_reg_624 <= i_5_reg_1977;
    end else if (((ap_ST_st13_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1163_p2))) begin
        i_10_reg_624 <= ap_const_lv3_0;
    end
    if ((ap_ST_st40_fsm_40 == ap_CS_fsm)) begin
        i_11_reg_2231 <= i_11_fu_1591_p2;
    end
    if ((ap_ST_st43_fsm_43 == ap_CS_fsm)) begin
        i_13_reg_2267 <= i_13_fu_1643_p2;
    end
    if ((ap_ST_st34_fsm_34 == ap_CS_fsm)) begin
        i_14_reg_2158 <= i_14_fu_1345_p2;
    end
    if ((ap_ST_st4_fsm_4 == ap_CS_fsm)) begin
        i_1_reg_1785 <= i_1_fu_855_p2;
    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        i_2_reg_1772 <= i_2_fu_812_p2;
    end
    if ((ap_ST_st13_fsm_13 == ap_CS_fsm)) begin
        i_3_cast_cast_reg_1948[0] <= i_3_cast_cast_fu_1159_p1[0];
        i_3_cast_cast_reg_1948[1] <= i_3_cast_cast_fu_1159_p1[1];
        i_3_cast_cast_reg_1948[2] <= i_3_cast_cast_fu_1159_p1[2];
    end
    if (((ap_ST_st14_fsm_14 == ap_CS_fsm) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond6_fu_1179_p2))) begin
        i_3_reg_602 <= i_4_reg_1956;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_861_p2))) begin
        i_3_reg_602 <= ap_const_lv3_0;
    end
    if ((ap_ST_st13_fsm_13 == ap_CS_fsm)) begin
        i_4_reg_1956 <= i_4_fu_1169_p2;
    end
    if ((ap_ST_st15_fsm_15 == ap_CS_fsm)) begin
        i_5_reg_1977 <= i_5_fu_1217_p2;
    end
    if ((ap_ST_st46_fsm_46 == ap_CS_fsm)) begin
        i_6_cast_cast_reg_2290[0] <= i_6_cast_cast_fu_1716_p1[0];
        i_6_cast_cast_reg_2290[1] <= i_6_cast_cast_fu_1716_p1[1];
        i_6_cast_cast_reg_2290[2] <= i_6_cast_cast_fu_1716_p1[2];
    end
    if (((ap_ST_st47_fsm_47 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond12_fu_1736_p2))) begin
        i_6_reg_737 <= i_7_reg_2298;
    end else if (((ap_ST_st18_fsm_18 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond9_fu_1266_p2))) begin
        i_6_reg_737 <= ap_const_lv3_0;
    end
    if ((ap_ST_st46_fsm_46 == ap_CS_fsm)) begin
        i_7_reg_2298 <= i_7_fu_1726_p2;
    end
    if ((ap_ST_st34_fsm_34 == ap_CS_fsm)) begin
        i_8_cast_cast_reg_2149[0] <= i_8_cast_cast_fu_1335_p1[0];
        i_8_cast_cast_reg_2149[1] <= i_8_cast_cast_fu_1335_p1[1];
        i_8_cast_cast_reg_2149[2] <= i_8_cast_cast_fu_1335_p1[2];
    end
    if ((ap_ST_st34_fsm_34 == ap_CS_fsm)) begin
        i_8_cast_reg_2144[0] <= i_8_cast_fu_1330_p1[0];
        i_8_cast_reg_2144[1] <= i_8_cast_fu_1330_p1[1];
        i_8_cast_reg_2144[2] <= i_8_cast_fu_1330_p1[2];
    end
    if (((ap_ST_st33_fsm_33 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_6_reg_2087))) begin
        i_8_reg_679 <= ap_const_lv3_0;
    end else if ((ap_ST_st39_fsm_39 == ap_CS_fsm)) begin
        i_8_reg_679 <= i_14_reg_2158;
    end
    if ((ap_ST_st19_fsm_19 == ap_CS_fsm)) begin
        i_9_reg_2082 <= i_9_fu_1282_p2;
    end
    if ((ap_ST_st2_fsm_2 == ap_CS_fsm)) begin
        i_cast_cast_reg_1764[0] <= i_cast_cast_fu_802_p1[0];
        i_cast_cast_reg_1764[1] <= i_cast_cast_fu_802_p1[1];
        i_cast_cast_reg_1764[2] <= i_cast_cast_fu_802_p1[2];
    end
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~ap_sig_bdd_116 & ~(exitcond3_fu_822_p2 == ap_const_lv1_0))) begin
        i_reg_517 <= i_2_reg_1772;
    end else if ((ap_ST_st1_fsm_1 == ap_CS_fsm)) begin
        i_reg_517 <= ap_const_lv3_0;
    end
    if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_1000_p2))) begin
        indvar1_reg_539 <= i_1_reg_1785;
    end else if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_806_p2))) begin
        indvar1_reg_539 <= ap_const_lv4_0;
    end
    if (((ap_ST_st43_fsm_43 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond13_fu_1637_p2))) begin
        indvar_reg_646 <= r_reg_2060;
    end else if (((ap_ST_st15_fsm_15 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_1211_p2))) begin
        indvar_reg_646 <= ap_const_lv4_0;
    end
    if (((ap_ST_st19_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond11_fu_1276_p2))) begin
        j11_reg_668 <= ap_const_lv3_0;
    end else if ((ap_ST_st22_fsm_22 == ap_CS_fsm)) begin
        j11_reg_668 <= j_9_reg_2094;
    end
    if (((ap_ST_st43_fsm_43 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond13_fu_1637_p2))) begin
        j12_reg_726 <= ap_const_lv3_0;
    end else if ((ap_ST_st45_fsm_45 == ap_CS_fsm)) begin
        j12_reg_726 <= j_14_reg_2275;
    end
    if (((ap_ST_st15_fsm_15 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_fu_1211_p2))) begin
        j_10_reg_635 <= ap_const_lv3_0;
    end else if ((ap_ST_st17_fsm_17 == ap_CS_fsm)) begin
        j_10_reg_635 <= j_6_reg_2045;
    end
    if ((ap_ST_st44_fsm_44 == ap_CS_fsm)) begin
        j_14_reg_2275 <= j_14_fu_1663_p2;
    end
    if (((ap_ST_st40_fsm_40 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond16_fu_1585_p2))) begin
        j_15_reg_701 <= ap_const_lv3_0;
    end else if ((ap_ST_st42_fsm_42 == ap_CS_fsm)) begin
        j_15_reg_701 <= j_16_reg_2239;
    end
    if ((ap_ST_st41_fsm_41 == ap_CS_fsm)) begin
        j_16_reg_2239 <= j_16_fu_1607_p2;
    end
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        j_2_cast_cast_reg_1882[0] <= j_2_cast_cast_fu_996_p1[0];
        j_2_cast_cast_reg_1882[1] <= j_2_cast_cast_fu_996_p1[1];
        j_2_cast_cast_reg_1882[2] <= j_2_cast_cast_fu_996_p1[2];
    end
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        j_2_reg_591 <= j_3_reg_1895;
    end else if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        j_2_reg_591 <= ap_const_lv3_0;
    end
    if ((ap_ST_st8_fsm_8 == ap_CS_fsm)) begin
        j_3_reg_1895 <= j_3_fu_1006_p2;
    end
    if (((ap_ST_st13_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_1163_p2))) begin
        j_4_reg_613 <= ap_const_lv3_0;
    end else if (((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199)) begin
        j_4_reg_613 <= j_5_fu_1185_p2;
    end
    if ((ap_ST_st16_fsm_16 == ap_CS_fsm)) begin
        j_6_reg_2045 <= j_6_fu_1233_p2;
    end
    if (((ap_ST_st46_fsm_46 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond10_fu_1720_p2))) begin
        j_7_reg_748 <= ap_const_lv3_0;
    end else if (((ap_ST_st48_fsm_48 == ap_CS_fsm) & ~(CipherText_full_n == ap_const_logic_0))) begin
        j_7_reg_748 <= j_8_reg_2306;
    end
    if ((ap_ST_st47_fsm_47 == ap_CS_fsm)) begin
        j_8_reg_2306 <= j_8_fu_1742_p2;
    end
    if ((ap_ST_st20_fsm_20 == ap_CS_fsm)) begin
        j_9_reg_2094 <= j_9_fu_1303_p2;
    end
    if (((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_806_p2))) begin
        j_reg_528 <= ap_const_lv3_0;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116)) begin
        j_reg_528 <= j_1_fu_828_p2;
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        p_addr1_reg_1857 <= p_addr1_fu_960_p5;
    end
    if ((ap_ST_st11_fsm_11 == ap_CS_fsm)) begin
        p_addr22_reg_1943 <= p_addr22_fu_1150_p2;
    end
    if (((ap_ST_st34_fsm_34 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond14_fu_1339_p2))) begin
        p_addr30_cast_reg_2168[0] <= p_addr30_cast_fu_1357_p1[0];
        p_addr30_cast_reg_2168[1] <= p_addr30_cast_fu_1357_p1[1];
        p_addr30_cast_reg_2168[2] <= p_addr30_cast_fu_1357_p1[2];
    end
    if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        p_addr31_cast_reg_2188[0] <= p_addr31_cast_fu_1367_p1[0];
        p_addr31_cast_reg_2188[1] <= p_addr31_cast_fu_1367_p1[1];
        p_addr31_cast_reg_2188[2] <= p_addr31_cast_fu_1367_p1[2];
    end
    if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        p_addr32_cast_reg_2198[0] <= p_addr32_cast_fu_1377_p1[0];
        p_addr32_cast_reg_2198[1] <= p_addr32_cast_fu_1377_p1[1];
        p_addr32_cast_reg_2198[2] <= p_addr32_cast_fu_1377_p1[2];
        p_addr32_cast_reg_2198[3] <= p_addr32_cast_fu_1377_p1[3];
    end
    if (((ap_ST_st41_fsm_41 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond17_fu_1601_p2))) begin
        p_addr34_cast_reg_2244[0] <= p_addr34_cast_fu_1624_p1[0];
        p_addr34_cast_reg_2244[1] <= p_addr34_cast_fu_1624_p1[1];
        p_addr34_cast_reg_2244[2] <= p_addr34_cast_fu_1624_p1[2];
        p_addr34_cast_reg_2244[3] <= p_addr34_cast_fu_1624_p1[3];
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        p_addr3_reg_1862 <= p_addr3_fu_972_p5;
    end
    if ((ap_ST_st7_fsm_7 == ap_CS_fsm)) begin
        p_addr5_reg_1867 <= p_addr5_fu_984_p5;
    end
    if ((ap_ST_st18_fsm_18 == ap_CS_fsm)) begin
        r_cast_cast_reg_2066[0] <= r_cast_cast_fu_1262_p1[0];
        r_cast_cast_reg_2066[1] <= r_cast_cast_fu_1262_p1[1];
        r_cast_cast_reg_2066[2] <= r_cast_cast_fu_1262_p1[2];
        r_cast_cast_reg_2066[3] <= r_cast_cast_fu_1262_p1[3];
    end
    if ((ap_ST_st18_fsm_18 == ap_CS_fsm)) begin
        r_reg_2060 <= r_fu_1256_p2;
    end
    if (((ap_ST_st23_fsm_23 == ap_CS_fsm) | (ap_ST_st35_fsm_35 == ap_CS_fsm))) begin
        reg_783 <= StateArray_q0;
    end
    if ((ap_ST_st28_fsm_28 == ap_CS_fsm)) begin
        reg_788 <= StateArray_q0;
    end else if (((ap_ST_st23_fsm_23 == ap_CS_fsm) | (ap_ST_st35_fsm_35 == ap_CS_fsm))) begin
        reg_788 <= StateArray_q1;
    end
    if ((ap_ST_st28_fsm_28 == ap_CS_fsm)) begin
        reg_795 <= StateArray_q1;
    end else if ((ap_ST_st24_fsm_24 == ap_CS_fsm)) begin
        reg_795 <= StateArray_q0;
    end
    if ((ap_ST_st36_fsm_36 == ap_CS_fsm)) begin
        tmp_10_reg_2208 <= tmp_10_fu_1489_p2;
    end
    if ((ap_ST_st36_fsm_36 == ap_CS_fsm)) begin
        tmp_12_reg_2213 <= tmp_12_fu_1539_p2;
    end
    if ((ap_ST_st36_fsm_36 == ap_CS_fsm)) begin
        tmp_13_reg_2218 <= tmp_13_fu_1575_p2;
    end
    if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        tmp_15_reg_2178 <= StateArray_q0[ap_const_lv32_7];
    end
    if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        tmp_16_reg_2183 <= StateArray_q1[ap_const_lv32_7];
    end
    if (((ap_ST_st19_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond11_fu_1276_p2))) begin
        tmp_6_reg_2087 <= tmp_6_fu_1288_p2;
    end
    if ((ap_ST_st25_fsm_25 == ap_CS_fsm)) begin
        x_1_reg_2114 <= StateArray_q0;
    end
    if ((ap_ST_st26_fsm_26 == ap_CS_fsm)) begin
        x_2_reg_2124 <= StateArray_q0;
    end
    if ((ap_ST_st27_fsm_27 == ap_CS_fsm)) begin
        x_3_reg_2134 <= StateArray_q0;
    end
end

/// CipherText_write assign process. ///
always @ (ap_CS_fsm or CipherText_full_n)
begin
    if (((ap_ST_st48_fsm_48 == ap_CS_fsm) & ~(CipherText_full_n == ap_const_logic_0))) begin
        CipherText_write = ap_const_logic_1;
    end else begin
        CipherText_write = ap_const_logic_0;
    end
end

/// ExpandedKey_address0 assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_822_p2 or ap_sig_bdd_116 or exitcond2_fu_861_p2 or exitcond7_fu_1000_p2 or exitcond8_fu_1227_p2 or exitcond15_fu_1657_p2 or p_addr10_cast_fu_845_p1 or p_addr3_cast_fu_879_p1 or p_addr7_cast_fu_913_p1 or p_addr11_cast_fu_1024_p1 or p_addr13_cast_fu_1056_p1 or p_addr14_cast_fu_1086_p1 or p_addr20_cast_fu_1134_p1 or p_addr22_cast_fu_1155_p1 or p_addr26_cast_fu_1250_p1 or p_addr40_cast_fu_1711_p1)
begin
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        ExpandedKey_address0 = p_addr22_cast_fu_1155_p1;
    end else if ((ap_ST_st11_fsm_11 == ap_CS_fsm)) begin
        ExpandedKey_address0 = p_addr20_cast_fu_1134_p1;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116)) begin
        ExpandedKey_address0 = p_addr10_cast_fu_845_p1;
    end else if (((ap_ST_st44_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond15_fu_1657_p2))) begin
        ExpandedKey_address0 = p_addr40_cast_fu_1711_p1;
    end else if (((ap_ST_st16_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
        ExpandedKey_address0 = p_addr26_cast_fu_1250_p1;
    end else if ((ap_ST_st10_fsm_10 == ap_CS_fsm)) begin
        ExpandedKey_address0 = p_addr14_cast_fu_1086_p1;
    end else if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        ExpandedKey_address0 = p_addr13_cast_fu_1056_p1;
    end else if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1000_p2))) begin
        ExpandedKey_address0 = p_addr11_cast_fu_1024_p1;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        ExpandedKey_address0 = p_addr7_cast_fu_913_p1;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_861_p2))) begin
        ExpandedKey_address0 = p_addr3_cast_fu_879_p1;
    end else begin
        ExpandedKey_address0 = p_addr22_cast_fu_1155_p1;
    end
end

/// ExpandedKey_address1 assign process. ///
always @ (ap_CS_fsm or exitcond2_fu_861_p2 or exitcond7_fu_1000_p2 or p_addr5_cast_fu_896_p1 or p_addr8_cast_fu_930_p1 or p_addr12_cast_fu_1034_p1 or p_addr16_cast_fu_1071_p1 or p_addr18_cast_fu_1107_p1)
begin
    if ((ap_ST_st10_fsm_10 == ap_CS_fsm)) begin
        ExpandedKey_address1 = p_addr18_cast_fu_1107_p1;
    end else if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        ExpandedKey_address1 = p_addr16_cast_fu_1071_p1;
    end else if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1000_p2))) begin
        ExpandedKey_address1 = p_addr12_cast_fu_1034_p1;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        ExpandedKey_address1 = p_addr8_cast_fu_930_p1;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_861_p2))) begin
        ExpandedKey_address1 = p_addr5_cast_fu_896_p1;
    end else begin
        ExpandedKey_address1 = p_addr18_cast_fu_1107_p1;
    end
end

/// ExpandedKey_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_822_p2 or ap_sig_bdd_116 or exitcond2_fu_861_p2 or exitcond7_fu_1000_p2 or exitcond8_fu_1227_p2 or exitcond15_fu_1657_p2)
begin
    if ((((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_861_p2)) | (ap_ST_st5_fsm_5 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1000_p2)) | (ap_ST_st9_fsm_9 == ap_CS_fsm) | (ap_ST_st10_fsm_10 == ap_CS_fsm) | (ap_ST_st11_fsm_11 == ap_CS_fsm) | ((ap_ST_st16_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_1227_p2)) | ((ap_ST_st44_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond15_fu_1657_p2)) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116) | (ap_ST_st12_fsm_12 == ap_CS_fsm))) begin
        ExpandedKey_ce0 = ap_const_logic_1;
    end else begin
        ExpandedKey_ce0 = ap_const_logic_0;
    end
end

/// ExpandedKey_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond2_fu_861_p2 or exitcond7_fu_1000_p2)
begin
    if ((((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_861_p2)) | (ap_ST_st5_fsm_5 == ap_CS_fsm) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1000_p2)) | (ap_ST_st9_fsm_9 == ap_CS_fsm) | (ap_ST_st10_fsm_10 == ap_CS_fsm))) begin
        ExpandedKey_ce1 = ap_const_logic_1;
    end else begin
        ExpandedKey_ce1 = ap_const_logic_0;
    end
end

/// ExpandedKey_d0 assign process. ///
always @ (ap_CS_fsm or Key_dout or exitcond3_fu_822_p2 or ap_sig_bdd_116 or TempKeyCol_2_2_reg_1926 or TempKeyCol_3_2_reg_1937)
begin
    if ((ap_ST_st12_fsm_12 == ap_CS_fsm)) begin
        ExpandedKey_d0 = TempKeyCol_3_2_reg_1937;
    end else if ((ap_ST_st11_fsm_11 == ap_CS_fsm)) begin
        ExpandedKey_d0 = TempKeyCol_2_2_reg_1926;
    end else if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116)) begin
        ExpandedKey_d0 = Key_dout;
    end else begin
        ExpandedKey_d0 = Key_dout;
    end
end

/// ExpandedKey_d1 assign process. ///
always @ (ap_CS_fsm or TempKeyCol_0_2_fu_1039_p2 or TempKeyCol_1_2_reg_1915)
begin
    if ((ap_ST_st10_fsm_10 == ap_CS_fsm)) begin
        ExpandedKey_d1 = TempKeyCol_1_2_reg_1915;
    end else if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        ExpandedKey_d1 = TempKeyCol_0_2_fu_1039_p2;
    end else begin
        ExpandedKey_d1 = TempKeyCol_1_2_reg_1915;
    end
end

/// ExpandedKey_we0 assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_822_p2 or ap_sig_bdd_116)
begin
    if (((ap_ST_st11_fsm_11 == ap_CS_fsm) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116) | (ap_ST_st12_fsm_12 == ap_CS_fsm))) begin
        ExpandedKey_we0 = ap_const_logic_1;
    end else begin
        ExpandedKey_we0 = ap_const_logic_0;
    end
end

/// ExpandedKey_we1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st9_fsm_9 == ap_CS_fsm) | (ap_ST_st10_fsm_10 == ap_CS_fsm))) begin
        ExpandedKey_we1 = ap_const_logic_1;
    end else begin
        ExpandedKey_we1 = ap_const_logic_0;
    end
end

/// Key_read assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_822_p2 or ap_sig_bdd_116)
begin
    if (((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116)) begin
        Key_read = ap_const_logic_1;
    end else begin
        Key_read = ap_const_logic_0;
    end
end

/// PlainText_read assign process. ///
always @ (ap_CS_fsm or exitcond6_fu_1179_p2 or ap_sig_bdd_199)
begin
    if (((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199)) begin
        PlainText_read = ap_const_logic_1;
    end else begin
        PlainText_read = ap_const_logic_0;
    end
end

/// RCon_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond2_fu_861_p2)
begin
    if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_861_p2))) begin
        RCon_ce0 = ap_const_logic_1;
    end else begin
        RCon_ce0 = ap_const_logic_0;
    end
end

/// SBox_address0 assign process. ///
always @ (ap_CS_fsm or tmp_fu_935_p1 or tmp_2_fu_945_p1 or tmp_s_fu_1325_p1)
begin
    if ((ap_ST_st21_fsm_21 == ap_CS_fsm)) begin
        SBox_address0 = tmp_s_fu_1325_p1;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        SBox_address0 = tmp_2_fu_945_p1;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        SBox_address0 = tmp_fu_935_p1;
    end else begin
        SBox_address0 = tmp_s_fu_1325_p1;
    end
end

/// SBox_address1 assign process. ///
always @ (ap_CS_fsm or tmp_1_fu_940_p1 or tmp_3_fu_950_p1)
begin
    if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        SBox_address1 = tmp_3_fu_950_p1;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        SBox_address1 = tmp_1_fu_940_p1;
    end else begin
        SBox_address1 = tmp_3_fu_950_p1;
    end
end

/// SBox_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st5_fsm_5 == ap_CS_fsm) | (ap_ST_st6_fsm_6 == ap_CS_fsm) | (ap_ST_st21_fsm_21 == ap_CS_fsm))) begin
        SBox_ce0 = ap_const_logic_1;
    end else begin
        SBox_ce0 = ap_const_logic_0;
    end
end

/// SBox_ce1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st5_fsm_5 == ap_CS_fsm) | (ap_ST_st6_fsm_6 == ap_CS_fsm))) begin
        SBox_ce1 = ap_const_logic_1;
    end else begin
        SBox_ce1 = ap_const_logic_0;
    end
end

/// StateArrayTmp_address0 assign process. ///
always @ (ap_CS_fsm or i_8_cast_reg_2144 or p_addr30_cast_reg_2168 or p_addr31_cast_reg_2188 or p_addr32_cast_reg_2198 or p_addr34_cast_fu_1624_p1 or exitcond17_fu_1601_p2)
begin
    if ((ap_ST_st39_fsm_39 == ap_CS_fsm)) begin
        StateArrayTmp_address0 = p_addr32_cast_reg_2198;
    end else if ((ap_ST_st38_fsm_38 == ap_CS_fsm)) begin
        StateArrayTmp_address0 = p_addr31_cast_reg_2188;
    end else if ((ap_ST_st37_fsm_37 == ap_CS_fsm)) begin
        StateArrayTmp_address0 = p_addr30_cast_reg_2168;
    end else if ((ap_ST_st36_fsm_36 == ap_CS_fsm)) begin
        StateArrayTmp_address0 = i_8_cast_reg_2144;
    end else if (((ap_ST_st41_fsm_41 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond17_fu_1601_p2))) begin
        StateArrayTmp_address0 = p_addr34_cast_fu_1624_p1;
    end else begin
        StateArrayTmp_address0 = p_addr32_cast_reg_2198;
    end
end

/// StateArrayTmp_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond17_fu_1601_p2)
begin
    if (((ap_ST_st36_fsm_36 == ap_CS_fsm) | ((ap_ST_st41_fsm_41 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond17_fu_1601_p2)) | (ap_ST_st39_fsm_39 == ap_CS_fsm) | (ap_ST_st37_fsm_37 == ap_CS_fsm) | (ap_ST_st38_fsm_38 == ap_CS_fsm))) begin
        StateArrayTmp_ce0 = ap_const_logic_1;
    end else begin
        StateArrayTmp_ce0 = ap_const_logic_0;
    end
end

/// StateArrayTmp_d0 assign process. ///
always @ (ap_CS_fsm or tmp_10_reg_2208 or tmp_12_reg_2213 or tmp_13_reg_2218 or tmp_7_fu_1438_p2)
begin
    if ((ap_ST_st39_fsm_39 == ap_CS_fsm)) begin
        StateArrayTmp_d0 = tmp_13_reg_2218;
    end else if ((ap_ST_st38_fsm_38 == ap_CS_fsm)) begin
        StateArrayTmp_d0 = tmp_12_reg_2213;
    end else if ((ap_ST_st37_fsm_37 == ap_CS_fsm)) begin
        StateArrayTmp_d0 = tmp_10_reg_2208;
    end else if ((ap_ST_st36_fsm_36 == ap_CS_fsm)) begin
        StateArrayTmp_d0 = tmp_7_fu_1438_p2;
    end else begin
        StateArrayTmp_d0 = tmp_7_fu_1438_p2;
    end
end

/// StateArrayTmp_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st36_fsm_36 == ap_CS_fsm) | (ap_ST_st39_fsm_39 == ap_CS_fsm) | (ap_ST_st37_fsm_37 == ap_CS_fsm) | (ap_ST_st38_fsm_38 == ap_CS_fsm))) begin
        StateArrayTmp_we0 = ap_const_logic_1;
    end else begin
        StateArrayTmp_we0 = ap_const_logic_0;
    end
end

/// StateArray_address0 assign process. ///
always @ (ap_CS_fsm or exitcond6_fu_1179_p2 or ap_sig_bdd_199 or StateArray_addr_reg_1982 or StateArray_addr_2_reg_1992 or StateArray_addr_4_reg_2002 or StateArray_addr_6_reg_2012 or StateArray_addr_8_reg_2022 or StateArray_addr_10_reg_2032 or StateArray_addr_13_reg_2050 or exitcond8_fu_1227_p2 or exitcond11_fu_1276_p2 or StateArray_addr_15_reg_2099 or exitcond_fu_1297_p2 or i_8_cast_fu_1330_p1 or exitcond14_fu_1339_p2 or p_addr31_cast_fu_1367_p1 or p_addr34_cast_reg_2244 or StateArray_addr_21_reg_2280 or exitcond15_fu_1657_p2 or exitcond12_fu_1736_p2 or p_addr24_cast_fu_1202_p1 or p_addr26_cast_fu_1250_p1 or p_addr29_cast_fu_1320_p1 or p_addr36_cast_fu_1680_p1 or p_addr27_cast_fu_1759_p1)
begin
    if ((ap_ST_st45_fsm_45 == ap_CS_fsm)) begin
        StateArray_address0 = StateArray_addr_21_reg_2280;
    end else if ((ap_ST_st42_fsm_42 == ap_CS_fsm)) begin
        StateArray_address0 = p_addr34_cast_reg_2244;
    end else if ((ap_ST_st22_fsm_22 == ap_CS_fsm)) begin
        StateArray_address0 = StateArray_addr_15_reg_2099;
    end else if ((ap_ST_st17_fsm_17 == ap_CS_fsm)) begin
        StateArray_address0 = StateArray_addr_13_reg_2050;
    end else if (((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199)) begin
        StateArray_address0 = p_addr24_cast_fu_1202_p1;
    end else if (((ap_ST_st47_fsm_47 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond12_fu_1736_p2))) begin
        StateArray_address0 = p_addr27_cast_fu_1759_p1;
    end else if (((ap_ST_st44_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond15_fu_1657_p2))) begin
        StateArray_address0 = p_addr36_cast_fu_1680_p1;
    end else if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        StateArray_address0 = p_addr31_cast_fu_1367_p1;
    end else if (((ap_ST_st34_fsm_34 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond14_fu_1339_p2))) begin
        StateArray_address0 = i_8_cast_fu_1330_p1;
    end else if (((ap_ST_st27_fsm_27 == ap_CS_fsm) | (ap_ST_st33_fsm_33 == ap_CS_fsm))) begin
        StateArray_address0 = StateArray_addr_10_reg_2032;
    end else if (((ap_ST_st26_fsm_26 == ap_CS_fsm) | (ap_ST_st32_fsm_32 == ap_CS_fsm))) begin
        StateArray_address0 = StateArray_addr_8_reg_2022;
    end else if (((ap_ST_st25_fsm_25 == ap_CS_fsm) | (ap_ST_st31_fsm_31 == ap_CS_fsm))) begin
        StateArray_address0 = StateArray_addr_6_reg_2012;
    end else if (((ap_ST_st24_fsm_24 == ap_CS_fsm) | (ap_ST_st30_fsm_30 == ap_CS_fsm))) begin
        StateArray_address0 = StateArray_addr_4_reg_2002;
    end else if (((ap_ST_st23_fsm_23 == ap_CS_fsm) | (ap_ST_st29_fsm_29 == ap_CS_fsm))) begin
        StateArray_address0 = StateArray_addr_2_reg_1992;
    end else if (((ap_ST_st20_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_1297_p2))) begin
        StateArray_address0 = p_addr29_cast_fu_1320_p1;
    end else if (((ap_ST_st28_fsm_28 == ap_CS_fsm) | ((ap_ST_st19_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond11_fu_1276_p2)))) begin
        StateArray_address0 = StateArray_addr_reg_1982;
    end else if (((ap_ST_st16_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
        StateArray_address0 = p_addr26_cast_fu_1250_p1;
    end else begin
        StateArray_address0 = p_addr34_cast_reg_2244;
    end
end

/// StateArray_address1 assign process. ///
always @ (ap_CS_fsm or StateArray_addr_1_reg_1987 or StateArray_addr_3_reg_1997 or StateArray_addr_5_reg_2007 or StateArray_addr_7_reg_2017 or StateArray_addr_9_reg_2027 or StateArray_addr_11_reg_2037 or exitcond11_fu_1276_p2 or exitcond14_fu_1339_p2 or p_addr30_cast_fu_1357_p1 or p_addr32_cast_fu_1377_p1)
begin
    if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        StateArray_address1 = p_addr32_cast_fu_1377_p1;
    end else if (((ap_ST_st34_fsm_34 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond14_fu_1339_p2))) begin
        StateArray_address1 = p_addr30_cast_fu_1357_p1;
    end else if (((ap_ST_st27_fsm_27 == ap_CS_fsm) | (ap_ST_st33_fsm_33 == ap_CS_fsm))) begin
        StateArray_address1 = StateArray_addr_11_reg_2037;
    end else if (((ap_ST_st26_fsm_26 == ap_CS_fsm) | (ap_ST_st32_fsm_32 == ap_CS_fsm))) begin
        StateArray_address1 = StateArray_addr_9_reg_2027;
    end else if (((ap_ST_st25_fsm_25 == ap_CS_fsm) | (ap_ST_st31_fsm_31 == ap_CS_fsm))) begin
        StateArray_address1 = StateArray_addr_7_reg_2017;
    end else if (((ap_ST_st24_fsm_24 == ap_CS_fsm) | (ap_ST_st30_fsm_30 == ap_CS_fsm))) begin
        StateArray_address1 = StateArray_addr_5_reg_2007;
    end else if (((ap_ST_st23_fsm_23 == ap_CS_fsm) | (ap_ST_st29_fsm_29 == ap_CS_fsm))) begin
        StateArray_address1 = StateArray_addr_3_reg_1997;
    end else if (((ap_ST_st28_fsm_28 == ap_CS_fsm) | ((ap_ST_st19_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond11_fu_1276_p2)))) begin
        StateArray_address1 = StateArray_addr_1_reg_1987;
    end else begin
        StateArray_address1 = p_addr32_cast_fu_1377_p1;
    end
end

/// StateArray_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond6_fu_1179_p2 or ap_sig_bdd_199 or exitcond8_fu_1227_p2 or exitcond11_fu_1276_p2 or exitcond_fu_1297_p2 or exitcond14_fu_1339_p2 or exitcond15_fu_1657_p2 or exitcond12_fu_1736_p2)
begin
    if (((ap_ST_st23_fsm_23 == ap_CS_fsm) | (ap_ST_st35_fsm_35 == ap_CS_fsm) | (ap_ST_st28_fsm_28 == ap_CS_fsm) | (ap_ST_st24_fsm_24 == ap_CS_fsm) | ((ap_ST_st16_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_1227_p2)) | ((ap_ST_st19_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond11_fu_1276_p2)) | ((ap_ST_st20_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_1297_p2)) | (ap_ST_st25_fsm_25 == ap_CS_fsm) | (ap_ST_st26_fsm_26 == ap_CS_fsm) | (ap_ST_st27_fsm_27 == ap_CS_fsm) | ((ap_ST_st34_fsm_34 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond14_fu_1339_p2)) | ((ap_ST_st44_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond15_fu_1657_p2)) | ((ap_ST_st47_fsm_47 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond12_fu_1736_p2)) | ((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199) | (ap_ST_st17_fsm_17 == ap_CS_fsm) | (ap_ST_st22_fsm_22 == ap_CS_fsm) | (ap_ST_st33_fsm_33 == ap_CS_fsm) | (ap_ST_st42_fsm_42 == ap_CS_fsm) | (ap_ST_st45_fsm_45 == ap_CS_fsm) | (ap_ST_st29_fsm_29 == ap_CS_fsm) | (ap_ST_st30_fsm_30 == ap_CS_fsm) | (ap_ST_st31_fsm_31 == ap_CS_fsm) | (ap_ST_st32_fsm_32 == ap_CS_fsm))) begin
        StateArray_ce0 = ap_const_logic_1;
    end else begin
        StateArray_ce0 = ap_const_logic_0;
    end
end

/// StateArray_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond11_fu_1276_p2 or exitcond14_fu_1339_p2)
begin
    if (((ap_ST_st23_fsm_23 == ap_CS_fsm) | (ap_ST_st35_fsm_35 == ap_CS_fsm) | (ap_ST_st28_fsm_28 == ap_CS_fsm) | (ap_ST_st24_fsm_24 == ap_CS_fsm) | ((ap_ST_st19_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond11_fu_1276_p2)) | (ap_ST_st25_fsm_25 == ap_CS_fsm) | (ap_ST_st26_fsm_26 == ap_CS_fsm) | (ap_ST_st27_fsm_27 == ap_CS_fsm) | ((ap_ST_st34_fsm_34 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond14_fu_1339_p2)) | (ap_ST_st33_fsm_33 == ap_CS_fsm) | (ap_ST_st29_fsm_29 == ap_CS_fsm) | (ap_ST_st30_fsm_30 == ap_CS_fsm) | (ap_ST_st31_fsm_31 == ap_CS_fsm) | (ap_ST_st32_fsm_32 == ap_CS_fsm))) begin
        StateArray_ce1 = ap_const_logic_1;
    end else begin
        StateArray_ce1 = ap_const_logic_0;
    end
end

/// StateArray_d0 assign process. ///
always @ (ap_CS_fsm or PlainText_dout or SBox_q0 or reg_788 or reg_795 or exitcond6_fu_1179_p2 or ap_sig_bdd_199 or StateArray_load_4_reg_2109 or StateArray_load_6_reg_2119 or StateArray_load_8_reg_2129 or StateArray_load_10_reg_2139 or StateArrayTmp_q0 or grp_fu_760_p2)
begin
    if ((ap_ST_st42_fsm_42 == ap_CS_fsm)) begin
        StateArray_d0 = StateArrayTmp_q0;
    end else if ((ap_ST_st33_fsm_33 == ap_CS_fsm)) begin
        StateArray_d0 = reg_795;
    end else if ((ap_ST_st32_fsm_32 == ap_CS_fsm)) begin
        StateArray_d0 = StateArray_load_10_reg_2139;
    end else if ((ap_ST_st31_fsm_31 == ap_CS_fsm)) begin
        StateArray_d0 = StateArray_load_8_reg_2129;
    end else if ((ap_ST_st30_fsm_30 == ap_CS_fsm)) begin
        StateArray_d0 = StateArray_load_6_reg_2119;
    end else if ((ap_ST_st29_fsm_29 == ap_CS_fsm)) begin
        StateArray_d0 = StateArray_load_4_reg_2109;
    end else if ((ap_ST_st28_fsm_28 == ap_CS_fsm)) begin
        StateArray_d0 = reg_788;
    end else if ((ap_ST_st22_fsm_22 == ap_CS_fsm)) begin
        StateArray_d0 = SBox_q0;
    end else if (((ap_ST_st17_fsm_17 == ap_CS_fsm) | (ap_ST_st45_fsm_45 == ap_CS_fsm))) begin
        StateArray_d0 = grp_fu_760_p2;
    end else if (((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199)) begin
        StateArray_d0 = PlainText_dout;
    end else begin
        StateArray_d0 = grp_fu_760_p2;
    end
end

/// StateArray_d1 assign process. ///
always @ (ap_CS_fsm or reg_783 or reg_788 or reg_795 or x_1_reg_2114 or x_2_reg_2124 or x_3_reg_2134)
begin
    if ((ap_ST_st33_fsm_33 == ap_CS_fsm)) begin
        StateArray_d1 = x_3_reg_2134;
    end else if ((ap_ST_st32_fsm_32 == ap_CS_fsm)) begin
        StateArray_d1 = reg_788;
    end else if ((ap_ST_st31_fsm_31 == ap_CS_fsm)) begin
        StateArray_d1 = x_2_reg_2124;
    end else if ((ap_ST_st30_fsm_30 == ap_CS_fsm)) begin
        StateArray_d1 = x_1_reg_2114;
    end else if ((ap_ST_st29_fsm_29 == ap_CS_fsm)) begin
        StateArray_d1 = reg_783;
    end else if ((ap_ST_st28_fsm_28 == ap_CS_fsm)) begin
        StateArray_d1 = reg_795;
    end else begin
        StateArray_d1 = x_3_reg_2134;
    end
end

/// StateArray_we0 assign process. ///
always @ (ap_CS_fsm or exitcond6_fu_1179_p2 or ap_sig_bdd_199)
begin
    if (((ap_ST_st28_fsm_28 == ap_CS_fsm) | ((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199) | (ap_ST_st17_fsm_17 == ap_CS_fsm) | (ap_ST_st22_fsm_22 == ap_CS_fsm) | (ap_ST_st33_fsm_33 == ap_CS_fsm) | (ap_ST_st42_fsm_42 == ap_CS_fsm) | (ap_ST_st45_fsm_45 == ap_CS_fsm) | (ap_ST_st29_fsm_29 == ap_CS_fsm) | (ap_ST_st30_fsm_30 == ap_CS_fsm) | (ap_ST_st31_fsm_31 == ap_CS_fsm) | (ap_ST_st32_fsm_32 == ap_CS_fsm))) begin
        StateArray_we0 = ap_const_logic_1;
    end else begin
        StateArray_we0 = ap_const_logic_0;
    end
end

/// StateArray_we1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st28_fsm_28 == ap_CS_fsm) | (ap_ST_st33_fsm_33 == ap_CS_fsm) | (ap_ST_st29_fsm_29 == ap_CS_fsm) | (ap_ST_st30_fsm_30 == ap_CS_fsm) | (ap_ST_st31_fsm_31 == ap_CS_fsm) | (ap_ST_st32_fsm_32 == ap_CS_fsm))) begin
        StateArray_we1 = ap_const_logic_1;
    end else begin
        StateArray_we1 = ap_const_logic_0;
    end
end

/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or CipherText_full_n or exitcond3_fu_822_p2 or ap_sig_bdd_116 or exitcond2_fu_861_p2 or exitcond7_fu_1000_p2 or exitcond6_fu_1179_p2 or ap_sig_bdd_199 or exitcond5_fu_1211_p2 or exitcond8_fu_1227_p2 or tmp_6_reg_2087 or exitcond11_fu_1276_p2 or exitcond_fu_1297_p2 or exitcond14_fu_1339_p2 or exitcond17_fu_1601_p2 or exitcond15_fu_1657_p2 or exitcond12_fu_1736_p2 or exitcond1_fu_806_p2 or exitcond4_fu_1163_p2 or exitcond13_fu_1637_p2 or exitcond9_fu_1266_p2 or exitcond16_fu_1585_p2 or exitcond10_fu_1720_p2)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st49_fsm_49 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st0_fsm_0;
    end else if (((ap_ST_st47_fsm_47 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond12_fu_1736_p2))) begin
        ap_NS_fsm = ap_ST_st48_fsm_48;
    end else if (((ap_ST_st46_fsm_46 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond10_fu_1720_p2))) begin
        ap_NS_fsm = ap_ST_st49_fsm_49;
    end else if ((((ap_ST_st48_fsm_48 == ap_CS_fsm) & ~(CipherText_full_n == ap_const_logic_0)) | ((ap_ST_st46_fsm_46 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond10_fu_1720_p2)))) begin
        ap_NS_fsm = ap_ST_st47_fsm_47;
    end else if (((ap_ST_st44_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond15_fu_1657_p2))) begin
        ap_NS_fsm = ap_ST_st45_fsm_45;
    end else if (((ap_ST_st45_fsm_45 == ap_CS_fsm) | ((ap_ST_st43_fsm_43 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond13_fu_1637_p2)))) begin
        ap_NS_fsm = ap_ST_st44_fsm_44;
    end else if (((ap_ST_st41_fsm_41 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond17_fu_1601_p2))) begin
        ap_NS_fsm = ap_ST_st42_fsm_42;
    end else if (((ap_ST_st42_fsm_42 == ap_CS_fsm) | ((ap_ST_st40_fsm_40 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond16_fu_1585_p2)))) begin
        ap_NS_fsm = ap_ST_st41_fsm_41;
    end else if ((ap_ST_st38_fsm_38 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st39_fsm_39;
    end else if ((ap_ST_st37_fsm_37 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st38_fsm_38;
    end else if ((ap_ST_st36_fsm_36 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st37_fsm_37;
    end else if ((ap_ST_st35_fsm_35 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st36_fsm_36;
    end else if ((((ap_ST_st34_fsm_34 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond14_fu_1339_p2)) | ((ap_ST_st41_fsm_41 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond17_fu_1601_p2)))) begin
        ap_NS_fsm = ap_ST_st40_fsm_40;
    end else if (((ap_ST_st34_fsm_34 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond14_fu_1339_p2))) begin
        ap_NS_fsm = ap_ST_st35_fsm_35;
    end else if ((((ap_ST_st40_fsm_40 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond16_fu_1585_p2)) | ((ap_ST_st33_fsm_33 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_6_reg_2087)) | ((ap_ST_st44_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond15_fu_1657_p2)))) begin
        ap_NS_fsm = ap_ST_st43_fsm_43;
    end else if (((ap_ST_st39_fsm_39 == ap_CS_fsm) | ((ap_ST_st33_fsm_33 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_6_reg_2087)))) begin
        ap_NS_fsm = ap_ST_st34_fsm_34;
    end else if ((ap_ST_st32_fsm_32 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st33_fsm_33;
    end else if ((ap_ST_st31_fsm_31 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st32_fsm_32;
    end else if ((ap_ST_st30_fsm_30 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st31_fsm_31;
    end else if ((ap_ST_st29_fsm_29 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st30_fsm_30;
    end else if ((ap_ST_st28_fsm_28 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st29_fsm_29;
    end else if ((ap_ST_st27_fsm_27 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st28_fsm_28;
    end else if ((ap_ST_st26_fsm_26 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st27_fsm_27;
    end else if ((ap_ST_st25_fsm_25 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st26_fsm_26;
    end else if ((ap_ST_st24_fsm_24 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st25_fsm_25;
    end else if ((ap_ST_st23_fsm_23 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st24_fsm_24;
    end else if ((ap_ST_st21_fsm_21 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st22_fsm_22;
    end else if (((ap_ST_st20_fsm_20 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_1297_p2))) begin
        ap_NS_fsm = ap_ST_st21_fsm_21;
    end else if (((ap_ST_st19_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond11_fu_1276_p2))) begin
        ap_NS_fsm = ap_ST_st23_fsm_23;
    end else if (((ap_ST_st22_fsm_22 == ap_CS_fsm) | ((ap_ST_st19_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond11_fu_1276_p2)))) begin
        ap_NS_fsm = ap_ST_st20_fsm_20;
    end else if ((((ap_ST_st18_fsm_18 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond9_fu_1266_p2)) | ((ap_ST_st47_fsm_47 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond12_fu_1736_p2)))) begin
        ap_NS_fsm = ap_ST_st46_fsm_46;
    end else if ((((ap_ST_st20_fsm_20 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_1297_p2)) | ((ap_ST_st18_fsm_18 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_1266_p2)))) begin
        ap_NS_fsm = ap_ST_st19_fsm_19;
    end else if (((ap_ST_st16_fsm_16 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
        ap_NS_fsm = ap_ST_st17_fsm_17;
    end else if ((((ap_ST_st15_fsm_15 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_fu_1211_p2)) | ((ap_ST_st43_fsm_43 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond13_fu_1637_p2)))) begin
        ap_NS_fsm = ap_ST_st18_fsm_18;
    end else if (((ap_ST_st17_fsm_17 == ap_CS_fsm) | ((ap_ST_st15_fsm_15 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_fu_1211_p2)))) begin
        ap_NS_fsm = ap_ST_st16_fsm_16;
    end else if ((((ap_ST_st13_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_1163_p2)) | ((ap_ST_st16_fsm_16 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_1227_p2)))) begin
        ap_NS_fsm = ap_ST_st15_fsm_15;
    end else if ((((ap_ST_st14_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_1179_p2) & ~ap_sig_bdd_199) | ((ap_ST_st13_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_1163_p2)))) begin
        ap_NS_fsm = ap_ST_st14_fsm_14;
    end else if ((ap_ST_st11_fsm_11 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st12_fsm_12;
    end else if ((ap_ST_st10_fsm_10 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st11_fsm_11;
    end else if ((ap_ST_st9_fsm_9 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st10_fsm_10;
    end else if (((ap_ST_st8_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_1000_p2))) begin
        ap_NS_fsm = ap_ST_st9_fsm_9;
    end else if (((ap_ST_st7_fsm_7 == ap_CS_fsm) | (ap_ST_st12_fsm_12 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st8_fsm_8;
    end else if ((ap_ST_st6_fsm_6 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st7_fsm_7;
    end else if ((ap_ST_st5_fsm_5 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st6_fsm_6;
    end else if ((((ap_ST_st4_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_861_p2)) | ((ap_ST_st14_fsm_14 == ap_CS_fsm) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond6_fu_1179_p2)))) begin
        ap_NS_fsm = ap_ST_st13_fsm_13;
    end else if (((ap_ST_st4_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_861_p2))) begin
        ap_NS_fsm = ap_ST_st5_fsm_5;
    end else if ((((ap_ST_st2_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_806_p2)) | ((ap_ST_st8_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_1000_p2)))) begin
        ap_NS_fsm = ap_ST_st4_fsm_4;
    end else if ((((ap_ST_st3_fsm_3 == ap_CS_fsm) & (exitcond3_fu_822_p2 == ap_const_lv1_0) & ~ap_sig_bdd_116) | ((ap_ST_st2_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_806_p2)))) begin
        ap_NS_fsm = ap_ST_st3_fsm_3;
    end else if (((ap_ST_st1_fsm_1 == ap_CS_fsm) | ((ap_ST_st3_fsm_3 == ap_CS_fsm) & ~ap_sig_bdd_116 & ~(exitcond3_fu_822_p2 == ap_const_lv1_0)))) begin
        ap_NS_fsm = ap_ST_st2_fsm_2;
    end else if ((((ap_ST_st0_fsm_0 == ap_CS_fsm) & (ap_const_logic_1 == ap_start)) | ((ap_const_logic_1 == ap_start) & (ap_ST_st49_fsm_49 == ap_CS_fsm)))) begin
        ap_NS_fsm = ap_ST_st1_fsm_1;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st49_fsm_49 == ap_CS_fsm)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st0_fsm_0 == ap_CS_fsm)) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end
assign CipherText_din = StateArray_q0;
assign RCon_address0 = indvar1_cast_fu_850_p1;
assign StateArray_addr_10_gep_fu_373_p3 = ap_const_lv32_D;
assign StateArray_addr_11_gep_fu_380_p3 = ap_const_lv32_C;
assign StateArray_addr_1_gep_fu_310_p3 = ap_const_lv32_5;
assign StateArray_addr_2_gep_fu_317_p3 = ap_const_lv32_6;
assign StateArray_addr_3_gep_fu_324_p3 = ap_const_lv32_7;
assign StateArray_addr_4_gep_fu_331_p3 = ap_const_lv32_8;
assign StateArray_addr_5_gep_fu_338_p3 = ap_const_lv32_A;
assign StateArray_addr_6_gep_fu_345_p3 = ap_const_lv32_9;
assign StateArray_addr_7_gep_fu_352_p3 = ap_const_lv32_B;
assign StateArray_addr_8_gep_fu_359_p3 = ap_const_lv32_F;
assign StateArray_addr_9_gep_fu_366_p3 = ap_const_lv32_E;
assign StateArray_addr_gep_fu_303_p3 = ap_const_lv32_4;
assign TempKeyCol_0_2_fu_1039_p2 = (ExpandedKey_q0 ^ TempKeyCol_0_1_reg_581);
assign TempKeyCol_0_fu_955_p2 = (RCon_load_reg_1832 ^ SBox_q0);
assign TempKeyCol_1_2_fu_1046_p2 = (ExpandedKey_q1 ^ TempKeyCol_1_1_reg_571);
assign TempKeyCol_2_2_fu_1076_p2 = (ExpandedKey_q0 ^ TempKeyCol_2_1_reg_561);
assign TempKeyCol_3_2_fu_1112_p2 = (ExpandedKey_q0 ^ TempKeyCol_3_1_reg_551);

/// ap_sig_bdd_116 assign process. ///
always @ (Key_empty_n or exitcond3_fu_822_p2)
begin
    ap_sig_bdd_116 = ((Key_empty_n == ap_const_logic_0) & (exitcond3_fu_822_p2 == ap_const_lv1_0));
end

/// ap_sig_bdd_199 assign process. ///
always @ (PlainText_empty_n or exitcond6_fu_1179_p2)
begin
    ap_sig_bdd_199 = ((PlainText_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond6_fu_1179_p2));
end
assign exitcond10_fu_1720_p2 = (i_6_reg_737 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond11_fu_1276_p2 = (i11_reg_657 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond12_fu_1736_p2 = (j_7_reg_748 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond13_fu_1637_p2 = (i12_reg_712 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond14_fu_1339_p2 = (i_8_reg_679 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond15_fu_1657_p2 = (j12_reg_726 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond16_fu_1585_p2 = (i13_reg_690 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond17_fu_1601_p2 = (j_15_reg_701 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond1_fu_806_p2 = (i_reg_517 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond2_fu_861_p2 = (indvar1_reg_539 == ap_const_lv4_A? 1'b1: 1'b0);
assign exitcond3_fu_822_p2 = (j_reg_528 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond4_fu_1163_p2 = (i_3_reg_602 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond5_fu_1211_p2 = (i_10_reg_624 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond6_fu_1179_p2 = (j_4_reg_613 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond7_fu_1000_p2 = (j_2_reg_591 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond8_fu_1227_p2 = (j_10_reg_635 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond9_fu_1266_p2 = (indvar_reg_646 == ap_const_lv4_A? 1'b1: 1'b0);
assign exitcond_fu_1297_p2 = (j11_reg_668 == ap_const_lv3_4? 1'b1: 1'b0);
assign grp_fu_760_p2 = (ExpandedKey_q0 ^ StateArray_q0);
assign grp_fu_767_p3 = StateArray_q0[ap_const_lv32_7];
assign grp_fu_775_p3 = StateArray_q1[ap_const_lv32_7];
assign i11_cast_cast_fu_1272_p1 = $unsigned(i11_reg_657);
assign i12_cast1_fu_1629_p1 = $unsigned(i12_reg_712);
assign i12_cast_fu_1633_p1 = $unsigned(i12_reg_712);
assign i13_cast_cast_fu_1581_p1 = $unsigned(i13_reg_690);
assign i_10_cast_cast_fu_1207_p1 = $unsigned(i_10_reg_624);
assign i_11_fu_1591_p2 = (i13_reg_690 + ap_const_lv3_1);
assign i_13_fu_1643_p2 = (i12_reg_712 + ap_const_lv3_1);
assign i_14_fu_1345_p2 = (i_8_reg_679 + ap_const_lv3_1);
assign i_1_fu_855_p2 = (indvar1_reg_539 + ap_const_lv4_1);
assign i_2_fu_812_p2 = (i_reg_517 + ap_const_lv3_1);
assign i_3_cast_cast_fu_1159_p1 = $unsigned(i_3_reg_602);
assign i_4_fu_1169_p2 = (i_3_reg_602 + ap_const_lv3_1);
assign i_5_fu_1217_p2 = (i_10_reg_624 + ap_const_lv3_1);
assign i_6_cast_cast_fu_1716_p1 = $unsigned(i_6_reg_737);
assign i_7_fu_1726_p2 = (i_6_reg_737 + ap_const_lv3_1);
assign i_8_cast_cast_fu_1335_p1 = $unsigned(i_8_reg_679);
assign i_8_cast_fu_1330_p1 = $unsigned(i_8_reg_679);
assign i_9_fu_1282_p2 = (i11_reg_657 + ap_const_lv3_1);
assign i_cast_cast_fu_802_p1 = $unsigned(i_reg_517);
assign iftmp_1_cast_cast_fu_1401_p3 = ((tmp_16_reg_2183)? ap_const_lv8_1B: ap_const_lv8_0);
assign iftmp_2_cast_cast_fu_1451_p3 = ((grp_fu_767_p3)? ap_const_lv8_1B: ap_const_lv8_0);
assign iftmp_3_cast_cast_fu_1501_p3 = ((grp_fu_775_p3)? ap_const_lv8_1B: ap_const_lv8_0);
assign iftmp_cast_cast_fu_1388_p3 = ((tmp_15_reg_2178)? ap_const_lv8_1B: ap_const_lv8_0);
assign indvar1_cast_fu_850_p1 = $unsigned(indvar1_reg_539);
assign j11_cast_cast_fu_1293_p1 = $unsigned(j11_reg_668);
assign j14_cast_cast1_fu_1649_p1 = $unsigned(j12_reg_726);
assign j14_cast_cast_fu_1653_p1 = $unsigned(j12_reg_726);
assign j_10_cast_cast_fu_1223_p1 = $unsigned(j_10_reg_635);
assign j_12_cast_cast_fu_1597_p1 = $unsigned(j_15_reg_701);
assign j_14_fu_1663_p2 = (j12_reg_726 + ap_const_lv3_1);
assign j_16_fu_1607_p2 = (j_15_reg_701 + ap_const_lv3_1);
assign j_1_fu_828_p2 = (j_reg_528 + ap_const_lv3_1);
assign j_2_cast_cast_fu_996_p1 = $unsigned(j_2_reg_591);
assign j_3_fu_1006_p2 = (j_2_reg_591 + ap_const_lv3_1);
assign j_4_cast_cast_fu_1175_p1 = $unsigned(j_4_reg_613);
assign j_5_fu_1185_p2 = (j_4_reg_613 + ap_const_lv3_1);
assign j_6_fu_1233_p2 = (j_10_reg_635 + ap_const_lv3_1);
assign j_7_cast_cast_fu_1732_p1 = $unsigned(j_7_reg_748);
assign j_8_fu_1742_p2 = (j_7_reg_748 + ap_const_lv3_1);
assign j_9_fu_1303_p2 = (j11_reg_668 + ap_const_lv3_1);
assign j_cast_cast_fu_818_p1 = $unsigned(j_reg_528);
assign p_addr10_cast_fu_845_p1 = $unsigned(p_addr8_fu_839_p2);
assign p_addr10_fu_1191_p2 = i_3_cast_cast_reg_1948 << ap_const_lv4_2;
assign p_addr11_cast_fu_1024_p1 = $unsigned(p_addr15_fu_1012_p5);
assign p_addr11_fu_1196_p2 = (p_addr10_fu_1191_p2 + j_4_cast_cast_fu_1175_p1);
assign p_addr12_cast_fu_1034_p1 = $unsigned(p_addr12_fu_1029_p2);
assign p_addr12_fu_1029_p2 = (p_addr1_reg_1857 + j_2_cast_cast_fu_996_p1);
assign p_addr13_cast_fu_1056_p1 = $unsigned(p_addr13_fu_1052_p2);
assign p_addr13_fu_1052_p2 = (p_addr3_reg_1862 | j_2_cast_cast_reg_1882);
assign p_addr14_cast_fu_1086_p1 = $unsigned(p_addr14_fu_1082_p2);
assign p_addr14_fu_1082_p2 = (p_addr5_reg_1867 + j_2_cast_cast_reg_1882);
assign p_addr15_fu_1012_p5 = {{indvar1_reg_539}, {j_2_cast_cast_fu_996_p1[32'd3 : 32'd0]}};
assign p_addr16_cast_fu_1071_p1 = $unsigned(p_addr16_fu_1061_p5);
assign p_addr16_fu_1061_p5 = {{i_1_reg_1785}, {j_2_cast_cast_reg_1882[32'd3 : 32'd0]}};
assign p_addr17_fu_1091_p5 = {{i_1_reg_1785}, {ap_const_lv8_4[32'd3 : 32'd0]}};
assign p_addr18_cast_fu_1107_p1 = $unsigned(p_addr18_fu_1102_p2);
assign p_addr18_fu_1102_p2 = (p_addr17_fu_1091_p5 + j_2_cast_cast_reg_1882);
assign p_addr19_fu_1118_p5 = {{i_1_reg_1785}, {ap_const_lv8_8[32'd3 : 32'd0]}};
assign p_addr1_fu_960_p5 = {{indvar1_reg_539}, {ap_const_lv8_4[32'd3 : 32'd0]}};
assign p_addr20_cast_fu_1134_p1 = $unsigned(p_addr20_fu_1129_p2);
assign p_addr20_fu_1129_p2 = (p_addr19_fu_1118_p5 | j_2_cast_cast_reg_1882);
assign p_addr21_fu_1139_p5 = {{i_1_reg_1785}, {ap_const_lv8_C[32'd3 : 32'd0]}};
assign p_addr22_cast_fu_1155_p1 = $unsigned(p_addr22_reg_1943);
assign p_addr22_fu_1150_p2 = (p_addr21_fu_1139_p5 + j_2_cast_cast_reg_1882);
assign p_addr23_fu_1239_p2 = i_10_cast_cast_reg_1969 << ap_const_lv4_2;
assign p_addr24_cast_fu_1202_p1 = $unsigned(p_addr11_fu_1196_p2);
assign p_addr24_fu_1244_p2 = (p_addr23_fu_1239_p2 + j_10_cast_cast_fu_1223_p1);
assign p_addr25_fu_1753_p2 = (p_addr_fu_1748_p2 + j_7_cast_cast_fu_1732_p1);
assign p_addr26_cast_fu_1250_p1 = $unsigned(p_addr24_fu_1244_p2);
assign p_addr26_fu_1309_p2 = i11_cast_cast_reg_2074 << ap_const_lv4_2;
assign p_addr27_cast_fu_1759_p1 = $unsigned(p_addr25_fu_1753_p2);
assign p_addr27_fu_1314_p2 = (p_addr26_fu_1309_p2 + j11_cast_cast_fu_1293_p1);
assign p_addr28_fu_1351_p2 = (i_8_reg_679 ^ ap_const_lv3_4);
assign p_addr29_cast_fu_1320_p1 = $unsigned(p_addr27_fu_1314_p2);
assign p_addr29_fu_1362_p2 = (i_8_cast_cast_reg_2149 | ap_const_lv4_8);
assign p_addr2_fu_867_p5 = {{indvar1_reg_539}, {ap_const_lv8_7[32'd3 : 32'd0]}};
assign p_addr30_cast_fu_1357_p1 = $unsigned(p_addr28_fu_1351_p2);
assign p_addr30_fu_1372_p2 = (i_8_cast_cast_reg_2149 + ap_const_lv4_C);
assign p_addr31_cast_fu_1367_p1 = $unsigned(p_addr29_fu_1362_p2);
assign p_addr31_fu_1669_p2 = i12_cast_reg_2259 << ap_const_lv4_2;
assign p_addr32_cast_fu_1377_p1 = $unsigned(p_addr30_fu_1372_p2);
assign p_addr32_fu_1674_p2 = (p_addr31_fu_1669_p2 + j14_cast_cast_fu_1653_p1);
assign p_addr33_fu_1613_p2 = i13_cast_cast_reg_2223 << ap_const_lv4_2;
assign p_addr34_cast_fu_1624_p1 = $unsigned(p_addr34_fu_1618_p2);
assign p_addr34_fu_1618_p2 = (p_addr33_fu_1613_p2 + j_12_cast_cast_fu_1597_p1);
assign p_addr35_fu_1685_p2 = r_cast_cast_reg_2066 << ap_const_lv6_2;
assign p_addr36_cast_fu_1680_p1 = $unsigned(p_addr32_fu_1674_p2);
assign p_addr36_fu_1690_p2 = (p_addr35_fu_1685_p2 + i12_cast1_reg_2254);
assign p_addr37_fu_1699_p2 = p_addr38_cast_fu_1695_p1 << ap_const_lv8_2;
assign p_addr38_cast_fu_1695_p1 = $unsigned(p_addr36_fu_1690_p2);
assign p_addr38_fu_1705_p2 = (p_addr37_fu_1699_p2 + j14_cast_cast1_fu_1649_p1);
assign p_addr3_cast_fu_879_p1 = $unsigned(p_addr2_fu_867_p5);
assign p_addr3_fu_972_p5 = {{indvar1_reg_539}, {ap_const_lv8_8[32'd3 : 32'd0]}};
assign p_addr40_cast_fu_1711_p1 = $unsigned(p_addr38_fu_1705_p2);
assign p_addr4_fu_884_p5 = {{indvar1_reg_539}, {ap_const_lv8_B[32'd3 : 32'd0]}};
assign p_addr5_cast_fu_896_p1 = $unsigned(p_addr4_fu_884_p5);
assign p_addr5_fu_984_p5 = {{indvar1_reg_539}, {ap_const_lv8_C[32'd3 : 32'd0]}};
assign p_addr6_fu_901_p5 = {{indvar1_reg_539}, {ap_const_lv8_F[32'd3 : 32'd0]}};
assign p_addr7_cast_fu_913_p1 = $unsigned(p_addr6_fu_901_p5);
assign p_addr7_fu_918_p5 = {{indvar1_reg_539}, {ap_const_lv8_3[32'd3 : 32'd0]}};
assign p_addr8_cast_fu_930_p1 = $unsigned(p_addr7_fu_918_p5);
assign p_addr8_fu_839_p2 = (p_addr9_fu_834_p2 + j_cast_cast_fu_818_p1);
assign p_addr9_fu_834_p2 = i_cast_cast_reg_1764 << ap_const_lv4_2;
assign p_addr_fu_1748_p2 = i_6_cast_cast_reg_2290 << ap_const_lv4_2;
assign r_cast_cast_fu_1262_p1 = $unsigned(r_fu_1256_p2);
assign r_fu_1256_p2 = (indvar_reg_646 + ap_const_lv4_1);
assign tmp10_fu_1483_p2 = (tmp9_fu_1477_p2 ^ tmp8_fu_1471_p2);
assign tmp11_fu_1509_p2 = (reg_783 ^ tmp_9_fu_1445_p2);
assign tmp12_fu_1515_p2 = (tmp11_fu_1509_p2 ^ reg_788);
assign tmp13_fu_1521_p2 = (iftmp_2_cast_cast_fu_1451_p3 ^ tmp_11_fu_1495_p2);
assign tmp14_fu_1527_p2 = (StateArray_q1 ^ iftmp_3_cast_cast_fu_1501_p3);
assign tmp15_fu_1533_p2 = (tmp14_fu_1527_p2 ^ tmp13_fu_1521_p2);
assign tmp16_fu_1545_p2 = (tmp_4_fu_1382_p2 ^ iftmp_cast_cast_fu_1388_p3);
assign tmp17_fu_1551_p2 = (tmp16_fu_1545_p2 ^ reg_783);
assign tmp18_fu_1557_p2 = (reg_788 ^ StateArray_q0);
assign tmp19_fu_1563_p2 = (tmp_11_fu_1495_p2 ^ iftmp_3_cast_cast_fu_1501_p3);
assign tmp1_fu_1408_p2 = (tmp_4_fu_1382_p2 ^ tmp_8_fu_1395_p2);
assign tmp20_fu_1569_p2 = (tmp19_fu_1563_p2 ^ tmp18_fu_1557_p2);
assign tmp2_fu_1414_p2 = (tmp1_fu_1408_p2 ^ iftmp_cast_cast_fu_1388_p3);
assign tmp3_fu_1420_p2 = (reg_788 ^ iftmp_1_cast_cast_fu_1401_p3);
assign tmp4_fu_1426_p2 = (StateArray_q0 ^ StateArray_q1);
assign tmp5_fu_1432_p2 = (tmp4_fu_1426_p2 ^ tmp3_fu_1420_p2);
assign tmp6_fu_1459_p2 = (reg_783 ^ iftmp_1_cast_cast_fu_1401_p3);
assign tmp7_fu_1465_p2 = (tmp6_fu_1459_p2 ^ tmp_8_fu_1395_p2);
assign tmp8_fu_1471_p2 = (tmp_9_fu_1445_p2 ^ StateArray_q0);
assign tmp9_fu_1477_p2 = (iftmp_2_cast_cast_fu_1451_p3 ^ StateArray_q1);
assign tmp_10_fu_1489_p2 = (tmp10_fu_1483_p2 ^ tmp7_fu_1465_p2);
assign tmp_11_fu_1495_p2 = StateArray_q1 << ap_const_lv8_1;
assign tmp_12_fu_1539_p2 = (tmp15_fu_1533_p2 ^ tmp12_fu_1515_p2);
assign tmp_13_fu_1575_p2 = (tmp20_fu_1569_p2 ^ tmp17_fu_1551_p2);
assign tmp_1_fu_940_p1 = $unsigned(ExpandedKey_q1);
assign tmp_2_fu_945_p1 = $unsigned(ExpandedKey_q0);
assign tmp_3_fu_950_p1 = $unsigned(ExpandedKey_q1);
assign tmp_4_fu_1382_p2 = reg_783 << ap_const_lv8_1;
assign tmp_6_fu_1288_p2 = (r_reg_2060 == ap_const_lv4_A? 1'b1: 1'b0);
assign tmp_7_fu_1438_p2 = (tmp5_fu_1432_p2 ^ tmp2_fu_1414_p2);
assign tmp_8_fu_1395_p2 = reg_788 << ap_const_lv8_1;
assign tmp_9_fu_1445_p2 = StateArray_q0 << ap_const_lv8_1;
assign tmp_fu_935_p1 = $unsigned(ExpandedKey_q0);
assign tmp_s_fu_1325_p1 = $unsigned(StateArray_q0);
always @ (posedge ap_clk)
begin
    i_cast_cast_reg_1764[3] <= 1'b0;
    j_2_cast_cast_reg_1882[7:3] <= 5'b00000;
    i_3_cast_cast_reg_1948[3] <= 1'b0;
    i_10_cast_cast_reg_1969[3] <= 1'b0;
    StateArray_addr_reg_1982[3:0] <= 4'b0100;
    StateArray_addr_1_reg_1987[3:0] <= 4'b0101;
    StateArray_addr_2_reg_1992[3:0] <= 4'b0110;
    StateArray_addr_3_reg_1997[3:0] <= 4'b0111;
    StateArray_addr_4_reg_2002[3:0] <= 4'b1000;
    StateArray_addr_5_reg_2007[3:0] <= 4'b1010;
    StateArray_addr_6_reg_2012[3:0] <= 4'b1001;
    StateArray_addr_7_reg_2017[3:0] <= 4'b1011;
    StateArray_addr_8_reg_2022[3:0] <= 4'b1111;
    StateArray_addr_9_reg_2027[3:0] <= 4'b1110;
    StateArray_addr_10_reg_2032[3:0] <= 4'b1101;
    StateArray_addr_11_reg_2037[3:0] <= 4'b1100;
    r_cast_cast_reg_2066[5:4] <= 2'b00;
    i11_cast_cast_reg_2074[3] <= 1'b0;
    i_8_cast_reg_2144[31:3] <= 29'b00000000000000000000000000000;
    i_8_cast_cast_reg_2149[3] <= 1'b0;
    p_addr30_cast_reg_2168[31:3] <= 29'b00000000000000000000000000000;
    p_addr31_cast_reg_2188[31:3] <= 29'b00000000000000000000000000001;
    p_addr32_cast_reg_2198[31:4] <= 28'b0000000000000000000000000000;
    i13_cast_cast_reg_2223[3] <= 1'b0;
    p_addr34_cast_reg_2244[31:4] <= 28'b0000000000000000000000000000;
    i12_cast1_reg_2254[5:3] <= 3'b000;
    i12_cast_reg_2259[3] <= 1'b0;
    i_6_cast_cast_reg_2290[3] <= 1'b0;
end



endmodule //encrypt

