
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.2 EDK_P.28xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Profiling Configuration parameters. These parameters
* can be overwritten thru run configuration in SDK
*
*******************************************************************/

#ifndef _PROFILE_CONFIG_H
#define _PROFILE_CONFIG_H

#define BINSIZE 4
#define CPU_FREQ_HZ 100000000
#define SAMPLE_FREQ_HZ 100000
#define TIMER_CLK_TICKS 1000
#define PROC_MICROBLAZE 1
#define PROFILE_TIMER_BASEADDR 0x83C00000
#define TIMER_CONNECT_INTC 1
#define INTC_BASEADDR 0x81800000
#define ENABLE_SYS_INTR 1
#define PROFILE_TIMER_INTR_ID 0
#define PROFILE_TIMER_INTR_MASK 0x1

#endif

/******************************************************************/

