// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.2
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ==============================================================


// ap_start
#define ap_start_BASEADDR 0x0000

// ap_done
#define ap_done_BASEADDR  0x0004

// ap_idle
#define ap_idle_BASEADDR  0x0008
